<?php
include("db_connect.php");

// Array of Mindanao provinces
$mindanao_provinces = array(
    'Agusan del Norte',
    'Agusan del Sur',
    'Basilan',
    'Bukidnon',
    'Camiguin',
    'Cotabato',
    'Davao de Oro',
    'Davao del Norte',
    'Davao del Sur',
    'Davao Occidental',
    'Davao Oriental',
    'Dinagat Islands',
    'Lanao del Norte',
    'Lanao del Sur',
    'Maguindanao',
    'Misamis Occidental',
    'Misamis Oriental',
    'Sarangani',
    'South Cotabato',
    'Sultan Kudarat',
    'Sulu',
    'Surigao del Norte',
    'Surigao del Sur',
    'Tawi-Tawi',
    'Zamboanga del Norte',
    'Zamboanga del Sur',
    'Zamboanga Sibugay'
);

// Array of municipalities/cities for each province
$municipalities = array(
    'Zamboanga del Sur' => array(
        'Aurora',
        'Bayog',
        'Dimataling',
        'Dinas',
        'Dumalinao',
        'Dumingag',
        'Guipos',
        'Josefina',
        'Kumalarang',
        'Labangan',
        'Lakewood',
        'Lapuyan',
        'Mahayag',
        'Margosatubig',
        'Midsalip',
        'Molave',
        'Pagadian City',
        'Pitogo',
        'Ramon Magsaysay',
        'San Miguel',
        'San Pablo',
        'Sominot',
        'Tabina',
        'Tambulig',
        'Tigbao',
        'Tukuran',
        'Vincenzo A. Sagun',
        'Zamboanga City'
    ),
    'Misamis Occidental' => array(
        'Aloran',
        'Baliangao',
        'Bonifacio',
        'Calamba',
        'Clarin',
        'Concepcion',
        'Don Victoriano Chiongbian',
        'Jimenez',
        'Lopez Jaena',
        'Oroquieta City',
        'Ozamiz City',
        'Panaon',
        'Plaridel',
        'Sapang Dalaga',
        'Sinacaban',
        'Tangub City',
        'Tudela'
    ),
    'Misamis Oriental' => array(
        'Alubijid',
        'Balingasag',
        'Balingoan',
        'Binuangan',
        'Cagayan de Oro City',
        'Claveria',
        'El Salvador City',
        'Gingoog City',
        'Gitagum',
        'Initao',
        'Jasaan',
        'Kinoguitan',
        'Lagonglong',
        'Laguindingan',
        'Libertad',
        'Lugait',
        'Magsaysay',
        'Manticao',
        'Medina',
        'Naawan',
        'Opol',
        'Salay',
        'Sugbongcogon',
        'Tagoloan',
        'Talisayan',
        'Villanueva'
    ),
    'Davao del Sur' => array(
        'Bansalan',
        'Davao City',
        'Digos City',
        'Hagonoy',
        'Kiblawan',
        'Magsaysay',
        'Malalag',
        'Matanao',
        'Padada',
        'Santa Cruz',
        'Sulop'
    ),
    'Davao del Norte' => array(
        'Asuncion',
        'Braulio E. Dujali',
        'Carmen',
        'Kapalong',
        'New Corella',
        'Panabo City',
        'Samal City',
        'San Isidro',
        'Santo Tomas',
        'Tagum City',
        'Talaingod'
    ),
    'Bukidnon' => array(
        'Baungon',
        'Cabanglasan',
        'Damulog',
        'Dangcagan',
        'Don Carlos',
        'Impasugong',
        'Kadingilan',
        'Kalilangan',
        'Kibawe',
        'Kitaotao',
        'Lantapan',
        'Libona',
        'Malaybalay City',
        'Malitbog',
        'Manolo Fortich',
        'Maramag',
        'Pangantucan',
        'Quezon',
        'San Fernando',
        'Sumilao',
        'Talakag',
        'Valencia City'
    ),
    'Agusan del Norte' => array(
        'Buenavista',
        'Butuan City',
        'Cabadbaran City',
        'Carmen',
        'Jabonga',
        'Kitcharao',
        'Las Nieves',
        'Magallanes',
        'Nasipit',
        'Remedios T. Romualdez',
        'Santiago',
        'Tubay'
    ),
    'Agusan del Sur' => array(
        'Bayugan City',
        'Bunawan',
        'Esperanza',
        'La Paz',
        'Loreto',
        'Prosperidad',
        'Rosario',
        'San Francisco',
        'San Luis',
        'Santa Josefa',
        'Sibagat',
        'Talacogon',
        'Trento',
        'Veruela'
    ),
    'Basilan' => array(
        'Akbar',
        'Al-Barka',
        'Hadji Mohammad Ajul',
        'Hadji Muhtamad',
        'Isabela City',
        'Lamitan City',
        'Lantawan',
        'Maluso',
        'Sumisip',
        'Tabuan-Lasa',
        'Tipo-Tipo',
        'Tuburan',
        'Ungkaya Pukan'
    ),
    'Camiguin' => array(
        'Catarman',
        'Guinsiliban',
        'Mahinog',
        'Mambajao',
        'Sagay'
    ),
    'Cotabato' => array(
        'Alamada',
        'Aleosan',
        'Antipas',
        'Arakan',
        'Banisilan',
        'Carmen',
        'Kabacan',
        'Kidapawan City',
        'Libungan',
        'M\'lang',
        'Magpet',
        'Makilala',
        'Matalam',
        'Midsayap',
        'Pigcawayan',
        'Pikit',
        'President Roxas',
        'Tulunan'
    ),
    'Davao de Oro' => array(
        'Compostela',
        'Laak',
        'Mabini',
        'Maco',
        'Maragusan',
        'Mawab',
        'Monkayo',
        'Montevista',
        'Nabunturan',
        'New Bataan',
        'Pantukan'
    ),
    'Davao Occidental' => array(
        'Don Marcelino',
        'Jose Abad Santos',
        'Malita',
        'Santa Maria',
        'Sarangani'
    ),
    'Davao Oriental' => array(
        'Baganga',
        'Banaybanay',
        'Boston',
        'Caraga',
        'Cateel',
        'Governor Generoso',
        'Lupon',
        'Manay',
        'Mati City',
        'San Isidro',
        'Tarragona'
    ),
    'Dinagat Islands' => array(
        'Basilisa',
        'Cagdianao',
        'Dinagat',
        'Libjo',
        'Loreto',
        'San Jose',
        'Tubajon'
    ),
    'Lanao del Norte' => array(
        'Bacolod',
        'Baloi',
        'Baroy',
        'Iligan City',
        'Kapatagan',
        'Kauswagan',
        'Kolambugan',
        'Lala',
        'Linamon',
        'Magsaysay',
        'Maigo',
        'Matungao',
        'Munai',
        'Nunungan',
        'Pantao Ragat',
        'Pantar',
        'Poona Piagapo',
        'Salvador',
        'Sapad',
        'Sultan Naga Dimaporo',
        'Tagoloan',
        'Tangcal',
        'Tubod'
    ),
    'Lanao del Sur' => array(
        'Amai Manabilang',
        'Bacolod-Kalawi',
        'Balabagan',
        'Balindong',
        'Bayang',
        'Binidayan',
        'Buadiposo-Buntong',
        'Bubong',
        'Bumbaran',
        'Butig',
        'Calanogas',
        'Ditsaan-Ramain',
        'Ganassi',
        'Kapai',
        'Kapatagan',
        'Lumba-Bayabao',
        'Lumbaca-Unayan',
        'Lumbatan',
        'Lumbayanague',
        'Madalum',
        'Madamba',
        'Maguing',
        'Malabang',
        'Marantao',
        'Marawi City',
        'Marogong',
        'Masiu',
        'Mulondo',
        'Pagayawan',
        'Piagapo',
        'Picong',
        'Poona Bayabao',
        'Pualas',
        'Saguiaran',
        'Sultan Dumalondong',
        'Tagoloan II',
        'Tamparan',
        'Taraka',
        'Tubaran',
        'Tugaya',
        'Wao'
    ),
    'Maguindanao' => array(
        'Ampatuan',
        'Barira',
        'Buldon',
        'Buluan',
        'Cotabato City',
        'Datu Abdullah Sangki',
        'Datu Anggal Midtimbang',
        'Datu Blah T. Sinsuat',
        'Datu Hoffer Ampatuan',
        'Datu Montawal',
        'Datu Odin Sinsuat',
        'Datu Paglas',
        'Datu Piang',
        'Datu Salibo',
        'Datu Saudi-Ampatuan',
        'Datu Unsay',
        'General Salipada K. Pendatun',
        'Guindulungan',
        'Kabuntalan',
        'Mamasapano',
        'Mangudadatu',
        'Matanog',
        'Northern Kabuntalan',
        'Pagalungan',
        'Paglat',
        'Pandag',
        'Parang',
        'Rajah Buayan',
        'Shariff Aguak',
        'Shariff Saydona Mustapha',
        'South Upi',
        'Sultan Kudarat',
        'Sultan Mastura',
        'Sultan sa Barongis',
        'Sultan Sumagka',
        'Talayan',
        'Upi'
    ),
    'Sarangani' => array(
        'Alabel',
        'Glan',
        'Kiamba',
        'Maasim',
        'Maitum',
        'Malapatan',
        'Malungon'
    ),
    'South Cotabato' => array(
        'Banga',
        'General Santos City',
        'Koronadal City',
        'Lake Sebu',
        'Norala',
        'Polomolok',
        'Santo Niño',
        'Surallah',
        'T\'Boli',
        'Tampakan',
        'Tantangan',
        'Tupi'
    ),
    'Sultan Kudarat' => array(
        'Bagumbayan',
        'Columbio',
        'Esperanza',
        'Isulan',
        'Kalamansig',
        'Lambayong',
        'Lebak',
        'Lutayan',
        'Palimbang',
        'President Quirino',
        'Senator Ninoy Aquino',
        'Tacurong City'
    ),
    'Sulu' => array(
        'Banguingui',
        'Hadji Panglima Tahil',
        'Indanan',
        'Jolo',
        'Kalingalan Caluang',
        'Lugus',
        'Luuk',
        'Maimbung',
        'Old Panamao',
        'Omar',
        'Pandami',
        'Panglima Estino',
        'Pangutaran',
        'Parang',
        'Pata',
        'Patikul',
        'Siasi',
        'Talipao',
        'Tapul'
    ),
    'Surigao del Norte' => array(
        'Alegria',
        'Bacuag',
        'Burgos',
        'Claver',
        'Dapa',
        'Del Carmen',
        'General Luna',
        'Gigaquit',
        'Mainit',
        'Malimono',
        'Pilar',
        'Placer',
        'San Benito',
        'San Francisco',
        'San Isidro',
        'Santa Monica',
        'Sison',
        'Socorro',
        'Surigao City',
        'Tagana-an',
        'Tubod'
    ),
    'Surigao del Sur' => array(
        'Barobo',
        'Bayabas',
        'Bislig City',
        'Cagwait',
        'Cantilan',
        'Carmen',
        'Carrascal',
        'Cortes',
        'Hinatuan',
        'Lanuza',
        'Lianga',
        'Lingig',
        'Madrid',
        'Marihatag',
        'San Agustin',
        'San Miguel',
        'Tagbina',
        'Tago',
        'Tandag City'
    ),
    'Tawi-Tawi' => array(
        'Bongao',
        'Languyan',
        'Mapun',
        'Panglima Sugala',
        'Sapa-Sapa',
        'Sibutu',
        'Simunul',
        'Sitangkai',
        'South Ubian',
        'Tandubas',
        'Turtle Islands'
    ),
    'Zamboanga del Norte' => array(
        'Baliguian',
        'Dapitan City',
        'Dipolog City',
        'Godod',
        'Gutalac',
        'Jose Dalman',
        'Kalawit',
        'Katipunan',
        'La Libertad',
        'Labason',
        'Leon B. Postigo',
        'Liloy',
        'Manukan',
        'Mutia',
        'Piñan',
        'Polanco',
        'President Manuel A. Roxas',
        'Rizal',
        'Salug',
        'Sergio Osmeña Sr.',
        'Siayan',
        'Sibuco',
        'Sibutad',
        'Sindangan',
        'Siocon',
        'Sirawai',
        'Tampilisan'
    ),
    'Zamboanga Sibugay' => array(
        'Alicia',
        'Buug',
        'Diplahan',
        'Imelda',
        'Ipil',
        'Kabasalan',
        'Mabuhay',
        'Malangas',
        'Naga',
        'Olutanga',
        'Payao',
        'Roseller Lim',
        'Siay',
        'Talusan',
        'Titay',
        'Tungawan'
    )
);

// Array of municipalities/cities for each province
$barangays = array(
    'Zamboanga del Sur' => array(
        'Molave' => array(
            'Alicia',
            'Bagong Argao',
            'Bagong Gutlang',
            'Blancia',
            'Bogo Capalaran',
            'Culo',
            'Dalaon',
            'Dipolo',
            'Lower Dimorok',
            'Upper Dimorok',
            'Gonosan',
            'Lantawan',
            'Lourdes',
            'Madasigon',
            'Makuguihon',
            'Maloloy-on',
            'Miligan',
            'Parasan',
            'Poblacion',
            'Santo Rosario',
            'Silangit',
            'Simata',
            'Sudlon'
        ),
        'Pagadian City' => array(
            'Alegria',
            'Balangasan',
            'Balintawak',
            'Baloyboan',
            'Banale',
            'Bogo',
            'Bomba',
            'Buenavista',
            'Bulawan',
            'Danlugan',
            'Dao',
            'Deborok',
            'Ditoray',
            'Dumagoc',
            'Gatas',
            'Gubac',
            'Kagawasan',
            'Kahayagan',
            'Kalasan',
            'Kawit',
            'La Suerte',
            'Lala',
            'Lenienza',
            'Lison Valley',
            'Lower Sibatang',
            'Lumad',
            'Macasing',
            'Manga',
            'San Jose District (Pob.)',
            'San Pedro District (Pob.)',
            'Santiago District (Pob.)',
            'Santo Niño District (Pob.)',
            'Tiguma',
            'Tuburan District (Pob.)',
            'White Beach'
        ),
        'Tambulig' => array(
            'Bagong Kauswagan',
            'Bagong Tabogon',
            'Calolot',
            'Dimalinao',
            'Fabian',
            'Happy Valley',
            'Kapalaran',
            'Libato',
            'Limamawan',
            'Lower Liasan',
            'Lower Lodiong',
            'Lower Tiparak',
            'Major Sabtal',
            'New Village',
            'Pelocuban',
            'Poblacion',
            'San Jose',
            'San Vicente',
            'Santo Niño',
            'Sumile',
            'Upper Liaison',
            'Upper Lodiong',
            'Upper Tiparak'
        )
    ),
    'Misamis Occidental' => array(
        'Tangub City' => array(
            'Aquino (Marcos)',
            'Balatacan',
            'Banglay',
            'Bintana',
            'Caniangan',
            'Catagan',
            'Dicamay',
            'Garang',
            'Guinabot',
            'Isidro',
            'Kalubian',
            'Kimat',
            'Labuyo',
            'Maquilao',
            'Matugnao',
            'Minsubong',
            'Owayan',
            'Panalsalan',
            'Pangabuan',
            'Poblacion I',
            'Poblacion II',
            'San Antonio',
            'San Apolinario',
            'San Vicente',
            'Silanga',
            'Silangon',
            'Silanga',
            'Sumirap',
            'Taguite',
            'Tugas',
            'Villa',
            'Villalin'
        ),
        'Ozamiz City' => array(
            '50th District (Pob.)',
            'Aguada (Pob.)',
            'Bacolod',
            'Baliangao',
            'Bongbong',
            'Bulao',
            'Calabayan',
            'Capucao C.',
            'Capucao P.',
            'Carangan',
            'Carmen',
            'Catadman-Manabay',
            'Cavinte',
            'Dalapang',
            'Diguan',
            'Dimaluna',
            'Doña Consuelo',
            'Ditoray',
            'Dumagoc',
            'Gatas',
            'Gubac',
            'Kagawasan',
            'Kahayagan',
            'Kalasan',
            'Kawit',
            'La Suerte',
            'Lala',
            'Lenienza',
            'Lison Valley',
            'Lower Sibatang',
            'Lumad',
            'Macasing',
            'Manga',
            'Pantaon',
            'San Antonio',
            'San Roque',
            'Santa Cruz',
            'Stimson Abordo (Pob.)',
            'Tabid',
            'Tinago',
            'Triunfo'
        )
    ),
    'Davao del Sur' => array(
        'Digos City' => array(
            'Aplaya',
            'Balabag',
            'Binaton',
            'Cogon',
            'Colorado',
            'Dawis',
            'Dulangan',
            'Goma',
            'Igpit',
            'Kapatagan',
            'Lungag',
            'Mahayag',
            'Matti',
            'Melilia',
            'Pagatin',
            'Pandanon',
            'Ruparan',
            'San Jose',
            'San Miguel',
            'Sinawilan',
            'Soong',
            'Tiguman',
            'Tres De Mayo',
            'Zone 1',
            'Zone 2',
            'Zone 3'
        ),
        'Santa Cruz' => array(
            'Astorga',
            'Bato',
            'Coronon',
            'Darong',
            'Inawayan',
            'Jose Rizal',
            'Matutungan',
            'Mintal',
            'Poblacion',
            'Sibulan',
            'Sinaragan',
            'Tagabuli',
            'Tibolo',
            'Tuban',
            'Zone 1',
            'Zone 2',
            'Zone 3'
        )
    ),
    'South Cotabato' => array(
        'Polomolok' => array(
            'Bentung',
            'Caniangan',
            'Crossing Palkan',
            'Glamang',
            'Kinilis',
            'Klinan 6',
            'Koronadal Proper',
            'Lapu',
            'Landan',
            'Lumbo',
            'Magsaysay',
            'Maligo',
            'Pagalungan',
            'Palkan',
            'Poblacion',
            'Rubber',
            'Silway 7',
            'Silway 8',
            'Sulit',
            'Upper Klinan'
        ),
        'Tupi' => array(
            'Acmonan',
            'Alegre',
            'Bololmala',
            'Bunao',
            'Cebuano',
            'Crossing Rubber',
            'Kabbon Takas',
            'Kagay',
            'Kandaga',
            'Linan',
            'Lunen',
            'Mabuhay',
            'Miasong',
            'Palian',
            'Poblacion',
            'Polonuling',
            'Simbo',
            'Tubeng'
        )
    ),
    'North Cotabato' => array(
        'Kabacan' => array(
            'Aringay',
            'Bangilan',
            'Buluan',
            'Cuyapon',
            'Dagupan',
            'Katidtuan',
            'Kayaga',
            'Kibawe',
            'Magatos',
            'Malanduague',
            'Nanga-an',
            'Osias',
            'Paatan',
            'Pedtad',
            'Poblacion',
            'Salapungan',
            'Simbuhay',
            'Simone',
            'Tamped'
        ),
        'Matalam' => array(
            'Arapan',
            'Arakan',
            'Bangbang',
            'Central Malamote',
            'Dalapitan',
            'Kilada',
            'Kimagango',
            'Lampayan',
            'Latagan',
            'Manubuan',
            'Marbel',
            'Mibantang',
            'New Alimodian',
            'New Pandan',
            'Poblacion',
            'Ilian',
            'Salvacion',
            'Santa Maria',
            'Sarayan',
            'State',
            'Taculen',
            'Tampulan',
            'Tantangan',
            'Tawantawan'
        )
    ),
    'Agusan del Sur' => array(
        'Bayugan City' => array(
            'Berseba',
            'Bucac',
            'Calaitan',
            'Charito',
            'Cagdianao',
            'Crossland',
            'Del Monte',
            'Don Mateo',
            'Fili',
            'Gamao',
            'Katipunan',
            'Lemery',
            'Magkiangkang',
            'Makapa',
            'Marfil',
            'Maygatasan',
            'Mt. Ararat',
            'Mt. Carmel',
            'Mt. Olive',
            'New Salem',
            'Noli',
            'Osmeña',
            'Poblacion',
            'Pinagalaan',
            'Sagmone',
            'Salbu',
            'Salvacion',
            'San Jose',
            'Santa Irene',
            'Santa Teresita',
            'Santo Niño',
            'Taglatawan',
            'Taglibas',
            'Tagubay',
            'Villa Undayon'
        ),
        'Sibagat' => array(
            'Afga',
            'Anahawan',
            'Banagbanag',
            'Del Rosario',
            'El Rio',
            'Ilihan',
            'Kioya',
            'Magkalape',
            'Magsaysay',
            'Mahayahay',
            'New Tubigon',
            'Padiay',
            'Perez',
            'Poblacion',
            'San Isidro',
            'San Vicente',
            'Santa Cruz',
            'Santa Maria',
            'Sinai',
            'Tabon-tabon',
            'Tag-uyango'
        )
    ),
    'Maguindanao del Norte' => array(
        'Sultan Kudarat' => array(
            'Alamada',
            'Banubo',
            'Bulalo',
            'Capiton',
            'Cebuano',
            'Daguma',
            'Ganassi',
            'Kakar',
            'Katidtuan',
            'Katuli',
            'Limbo',
            'Ladia',
            'Matiompong',
            'Mulaug',
            'Narra',
            'Olas',
            'Poblacion',
            'Rebuken',
            'Simuay',
            'Simuay Seashore',
            'Sungkay',
            'Tapayan',
            'Timbangan',
            'Tukay',
            'Tumaga'
        ),
        'Sultan Mastura' => array(
            'Balut',
            'Boliok',
            'Bungabong',
            'Dagurongan',
            'Kirkir',
            'Macabiso',
            'Namuken',
            'Simuay Seashore',
            'Solon',
            'Taguilon',
            'Tapayan',
            'Tariken',
            'Tuka'
        ),
        'Parang' => array(
            'Poblacion I',
            'Poblacion II',
            'Poblacion III',
            'Poblacion IV',
            'Gadungan',
            'Guiday',
            'Gumagadong Calawag',
            'Landasan',
            'Litawan',
            'Making',
            'Manion',
            'Matibay',
            'Nituan',
            'Orandang',
            'Pinantao',
            'Polloc',
            'Sarmiento',
            'Tagudtongan',
            'Tuca-Maror',
            'Bongo Island',
            'Campo Islam',
            'Limbayan',
            'Macasandag',
            'Talisawa',
            'Tapian'
        ),
        'Matanog' => array(
            'Bayanga Norte',
            'Bayanga Sur',
            'Bugasan Norte',
            'Bugasan Sur',
            'Kidama',
            'Langco',
            'Sapad',
            'Poblacion'
        )
    ),
    'Maguindanao del Sur' => array(
        'Datu Saudi-Ampatuan' => array(
            'Dapiawan',
            'Elian',
            'Ganta',
            'Kabengi',
            'Kitango',
            'Kitapok',
            'Madia',
            'Pagatin',
            'Poblacion',
            'Salbu',
            'Sambulawan',
            'Sugadol',
            'Timbangan',
            'Tomicor'
        ),
        'Datu Odin Sinsuat' => array(
            'Ambolodto',
            'Awang',
            'Badak',
            'Bagoenged',
            'Bulao',
            'Buluan',
            'Dado',
            'Dinaig',
            'Dulangan',
            'Kakar',
            'Kapinpilan',
            'Kurintem',
            'Labungan',
            'Linek',
            'Makir',
            'Margues',
            'Poblacion',
            'Semba',
            'Sibuto',
            'Sifaren',
            'Tambak',
            'Tanuel',
            'Tapian',
            'Taviran',
            'Tempura',
            'Tran'
        )
    ),
    'Lanao del Sur' => array(
        'Butig' => array(
            'Butig Proper',
            'Cabasaran',
            'Coloyan Tambo',
            'Dilabayan',
            'Dolangan',
            'Malungun',
            'Pindolonan',
            'Poktan',
            'Ragayan',
            'Raya',
            'Sandab',
            'Samer',
            'Sundig',
            'Timbab',
            'Tiongko',
            'Tiporog'
        ),
        'Lumbayanague' => array(
            'Balagunan',
            'Barit',
            'Cadayonan',
            'Calipapa',
            'Dilausan',
            'Lumbac',
            'Lunay',
            'Macadar',
            'Malungun',
            'Minanga-Tambo',
            'Pagalongan',
            'Paganayan',
            'Poblacion',
            'Picotaan',
            'Punud',
            'Salipongan',
            'Sultan Gumander',
            'Unayan'
        )
    ),
    'Sulu' => array(
        'Patikul' => array(
            'Anuling',
            'Bangkal',
            'Batu-Batu',
            'Bawis',
            'Buli-Buli',
            'Bungkaung',
            'Danag',
            'Ganassi',
            'Kadday',
            'Kapuk',
            'Kiput',
            'Kusain',
            'Lahing-Lahing',
            'Latih-Latih',
            'Ligayan',
            'Lunggang',
            'Maligay',
            'Mangal',
            'Mantan',
            'Manubul',
            'Marang',
            'Mipantaw',
            'Pandan-Pandan',
            'Pangdan',
            'Pansul',
            'Parang',
            'Poblacion',
            'Punungan',
            'Saidu',
            'Sambulawan',
            'Sandah',
            'Santa Maria',
            'Sapah Malaum',
            'Sipangkot',
            'Sitangkai',
            'Talipao',
            'Tandu-Bagua',
            'Tandu-Bato',
            'Tangkuan',
            'Tapian',
            'Tarawakan',
            'Timpok',
            'Tugas',
            'Tukay',
            'Tumangas',
            'Tunhud',
            'Upper Sinumaan'
        ),
        'Talipao' => array(
            'Andalan',
            'Bandang',
            'Bilaan',
            'Buluan',
            'Buli-Buli',
            'Buluan',
            'Kapok-Pok',
            'Kipungot',
            'Kitaab',
            'Kiutaan',
            'Lalatan',
            'Lawaan',
            'Lumbaan Maarom',
            'Lumbaan Sigay',
            'Mali Layan',
            'Manga',
            'Manting',
            'Minis',
            'Poblacion',
            'Punay',
            'Punungan',
            'Putun Mahayag',
            'Sambang',
            'Sapah Malaum',
            'Sipangkot',
            'Talipao Proper',
            'Tampakan',
            'Tangkuan',
            'Tikong',
            'Tinggah',
            'Tubig Dakula',
            'Tubig Parang',
            'Tubig Sa Ka',
            'Tukay',
            'Tumangas',
            'Tunhoh',
            'Ungus-Ungus'
        )
    ),
    'Tawi-Tawi' => array(
        'Bongao' => array(
            'Ipil',
            'Kamagong',
            'Karungdong',
            'Kasalamatan',
            'Lamion',
            'Lakid',
            'Lambang',
            'Lapid-Lapid',
            'Laug',
            'Luuk Pandan',
            'Mandulan',
            'Masantong',
            'Pababag',
            'Pagasinan',
            'Pahut',
            'Pasiagan',
            'Sanga-Sanga',
            'Simandagit',
            'Sumangat',
            'Tarawakan',
            'Tongsinah',
            'Tubig Basag',
            'Tubig-Boh',
            'Tubig-Mampallam'
        ),
        'Panglima Sugala' => array(
            'Poblacion',
            'Balimbing',
            'Banban',
            'Batu-Batu',
            'Buan',
            'Dungon',
            'Kulape',
            'Ligayas',
            'Luuk Buntal',
            'Luuk Mampallam',
            'Luuk Tandu',
            'Malassa',
            'Parangan',
            'Sukah-Bulan',
            'Tandu Bato',
            'Tandu Owak',
            'Tundon',
            'Tungbangkaw',
            'Tunggusong'
        )
    ),
    'Zamboanga del Sur' => array(
        'Pagadian City' => array(
            'Alegria',
            'Balangasan',
            'Balintawak',
            'Baloyboan',
            'Banale',
            'Bogo',
            'Bomba',
            'Buenavista',
            'Bulatok',
            'Dampalan',
            'Danlugan',
            'Dao',
            'Datagan',
            'Deborok',
            'Ditoray',
            'Dumagoc',
            'Gatas',
            'Gubac',
            'Kagawasan',
            'Kahayagan',
            'Kalasan',
            'Kawit',
            'Lala',
            'Lenienza',
            'Lison Valley',
            'Lower Sibatang',
            'Lumad',
            'Macasing',
            'Manga',
            'Muricay',
            'Napolan',
            'Palpalan',
            'Poblacion',
            'Poloyagan',
            'San Jose',
            'San Pedro',
            'Santa Cruz',
            'Santiago',
            'Tiguma',
            'Tuburan',
            'Upper Sibatang',
            'White Beach'
        ),
        'Zamboanga City' => array(
            'Abong-Abong',
            'Arena Blanco',
            'Ayala',
            'Baliwasan',
            'Baluno',
            'Boalan',
            'Bolong',
            'Buenavista',
            'Bunguiao',
            'Cacao',
            'Calarian',
            'Campo Islam',
            'Capisan',
            'Cawit',
            'Culianan',
            'Curuan',
            'Daap',
            'Dita',
            'Divisoria',
            'Dulian',
            'Guisao',
            'Guiwan',
            'Kasanyangan',
            'La Paz',
            'Labuan',
            'Lamisahan',
            'Landang Gua',
            'Lanzones',
            'Lapakan',
            'Latuan',
            'Licomo',
            'Limaong',
            'Limpapa',
            'Lubigan',
            'Lumayang',
            'Maasin',
            'Malagutay',
            'Mampang',
            'Manalipa',
            'Mariki',
            'Mercedes',
            'Muti',
            'Pamucutan',
            'Pangapuyan',
            'Panubigan',
            'Pasilmanta',
            'Pasonanca',
            'Patalon',
            'Putik',
            'Quiniput',
            'Recodo',
            'Rio Hondo',
            'Salaan',
            'San Jose Cawa-Cawa',
            'San Jose Gusu',
            'San Ramon',
            'San Roque',
            'Sangali',
            'Santa Barbara',
            'Santa Catalina',
            'Santa Maria',
            'Santo Niño',
            'Sibulao',
            'Sinubong',
            'Sinunuc',
            'Tagasilay',
            'Taguiti',
            'Talabaan',
            'Talisayan',
            'Talon-Talon',
            'Taluksangay',
            'Tetuan',
            'Tictapul',
            'Tigbalabag',
            'Tigtabon',
            'Tolosa',
            'Tugbungan',
            'Tumalutab',
            'Tumitus',
            'Victoria',
            'Vitali',
            'Zambowood',
            'Zone I',
            'Zone II',
            'Zone III',
            'Zone IV'
        )
    ),
    'Misamis Oriental' => array(
        'Cagayan de Oro City' => array(
            'Agusan',
            'Balulang',
            'Bayabas',
            'Bonbon',
            'Bugo',
            'Bulua',
            'Camaman-an',
            'Carmen',
            'Consolacion',
            'Cugman',
            'Gusa',
            'Indahag',
            'Iponan',
            'Kauswagan',
            'Lapasan',
            'Lumbia',
            'Macabalan',
            'Macasandig',
            'Nazareth',
            'Patag',
            'Pigsag-an',
            'Puerto',
            'Puntod',
            'San Jose',
            'San Simon',
            'Tablon',
            'Tignapoloan',
            'Tuburan',
            'Zone 1',
            'Zone 2',
            'Zone 3',
            'Zone 4'
        ),
        'El Salvador City' => array(
            'Amao',
            'Bolisong',
            'Cogon',
            'Himaya',
            'Hinigdaan',
            'Kalabaylabay',
            'Kibonbon',
            'Molugan',
            'Poblacion',
            'Sambulawan',
            'Sinaloc',
            'Taytay',
            'Ulaliman',
            'Vista Grande'
        )
    ),
    'Bukidnon' => array(
        'Malaybalay City' => array(
            'Aglayan',
            'Bangcud',
            'Busdi',
            'Cabangahan',
            'Canasugan',
            'Capitan Angel',
            'Dalwangan',
            'Imbayao',
            'Kalasungay',
            'Kulaman',
            'Laguitas',
            'Linabo',
            'Magsaysay',
            'Managok',
            'Manalog',
            'Mapayag',
            'Miglamin',
            'Patpat',
            'Poblacion',
            'Saint Peter',
            'San Jose',
            'San Martin',
            'Santo Niño',
            'Silae',
            'Simaya',
            'Sumpong',
            'Violeta',
            'Zamboanguita'
        ),
        'Valencia City' => array(
            'Bagonta-as',
            'Barobo',
            'Batangan',
            'Colonia',
            'Guinoyoran',
            'Kahaponan',
            'Kilabong',
            'Lilingayon',
            'Lumbo',
            'Lurogan',
            'Maapag',
            'Mabuhay',
            'Mailag',
            'Mt. Nebo',
            'Nabag-o',
            'Pinatilan',
            'Poblacion',
            'San Carlos',
            'Sinabuagan',
            'Sugod',
            'Tongantongan',
            'Tugaya',
            'Vintar'
        )
    ),
    'Dinagat Islands' => array(
        'San Jose' => array(
            'Aurora (Pob.)',
            'Aurelio (Pob.)',
            'Cuarinta',
            'Don Ruben',
            'Jacquez',
            'Luna',
            'Mahayahay',
            'Matingbe',
            'San Jose (Pob.)',
            'San Juan (Pob.)',
            'San Pablo (Pob.)',
            'Sta. Cruz',
            'Wilson'
        ),
        'Basilisa' => array(
            'Benglen',
            'Catadman',
            'Cortes',
            'Doña Helen',
            'Edera',
            'Geotina',
            'Imee',
            'Melgar',
            'Navarro',
            'Osmeña',
            'Poblacion',
            'Puerto Princesa',
            'Rita',
            'Roxas',
            'San Miguel',
            'Sering',
            'Sombrado',
            'Tag-abaca',
            'Villa',
            'Villa Ecleo'
        )
    ),
    'Agusan del Norte' => array(
        'Nasipit' => array(
            'Aclan',
            'Amontay',
            'Ata-atahon',
            'Camagong',
            'Cubi-cubi',
            'Culit',
            'Jaguimitan',
            'Kinabjangan',
            'Punta',
            'Santa Ana',
            'Talisay',
            'Triangulo'
        ),
        'Buenavista' => array(
            'Abilan',
            'Alubijid',
            'Guinabsan',
            'Lower Olave',
            'Macalang',
            'Malapong',
            'Manapa',
            'Poblacion 1',
            'Poblacion 2',
            'Poblacion 3',
            'Poblacion 4',
            'Poblacion 5',
            'Poblacion 6',
            'Poblacion 7',
            'Poblacion 8',
            'Poblacion 9',
            'Rizal',
            'Simbalan',
            'Talo-ao',
            'Upper Olave'
        )
    ),
    'Surigao del Norte' => array(
        'Surigao City' => array(
            'Alegria',
            'Alipao',
            'Alunan',
            'Anomar',
            'Bailongon',
            'Baybay',
            'Bitaugan',
            'Bonifacio',
            'Cagniog',
            'Capucao',
            'Catadman',
            'Danao',
            'Ipil',
            'Lipata',
            'Luna',
            'Mabini',
            'Mabua',
            'Manjagao',
            'Mapawa',
            'Mat-i',
            'Nabago',
            'Nonoc',
            'Poctoy',
            'Punta Bilar',
            'Quezon',
            'Rizal',
            'Sabang',
            'San Juan',
            'Serna',
            'Sidlakan',
            'Silop',
            'Sugbay',
            'Taft',
            'Talisay',
            'Trinidad',
            'Washington',
            'Zaragoza'
        ),
        'Claver' => array(
            'Bagakay',
            'Cabugo',
            'Cagdianao',
            'Daywan',
            'Hayanggabon',
            'Ladgaron',
            'Magallanes',
            'Panatao',
            'Poblacion',
            'Sapa',
            'Taganito',
            'Urbiztondo',
            'Wangke'
        )
    ),
    'Surigao del Sur' => array(
        'Tandag City' => array(
            'Awasian',
            'Bagong Lungsod',
            'Bioto',
            'Bongtud',
            'Buenavista',
            'Dagocdoc',
            'Mabuhay',
            'Maitum',
            'Maticdum',
            'Pandanon',
            'Pangi',
            'Poblacion',
            'Rosario',
            'Salvacion',
            'San Agustin Norte',
            'San Antonio',
            'San Isidro',
            'San Jose',
            'San Miguel',
            'San Roque',
            'Telaje'
        ),
        'Bislig City' => array(
            'Bucto',
            'Burboanan',
            'Caguyao',
            'Coleto',
            'Comawas',
            'Kahayag',
            'Labasan',
            'Lawigan',
            'Maharlika',
            'Mangagoy',
            'Mone',
            'Pamanlinan',
            'Pamaypayan',
            'Poblacion',
            'San Antonio',
            'San Fernando',
            'San Isidro',
            'San Jose',
            'San Roque',
            'San Vicente',
            'Santa Cruz',
            'Sibagat',
            'Tabon'
        )
    ),
    'Misamis Oriental' => array(
        'Gingoog City' => array(
            'Agay-ayan',
            'Alagatan',
            'Anakan',
            'Bagubad',
            'Bal-ason',
            'Baliwagan',
            'Binuangan',
            'Bunawan',
            'Calacapan',
            'Cagayan',
            'Ginoong',
            'Kipit',
            'Libertad',
            'Lunao',
            'Odiongan',
            'Pangasihan',
            'Poblacion',
            'Punong',
            'Ricardo P. Brioso',
            'Samay',
            'San Jose',
            'San Luis',
            'San Miguel',
            'Santiago',
            'Tagasilay',
            'Tagbiti',
            'Talisayan'
        ),
        'Tagoloan' => array(
            'Baluarte',
            'Casinglot',
            'Gracia',
            'Mohon',
            'Naruangan',
            'Poblacion',
            'Rosario',
            'Santa Ana',
            'Santa Cruz',
            'Sugbongcogon'
        )
    ),
    'Bukidnon' => array(
        'Don Carlos' => array(
            'Bocboc',
            'Buyot',
            'Calamagun',
            'Kalubihon',
            'Kibatang',
            'Kiputi',
            'Kisandig',
            'Kitaotao',
            'Kumalagko',
            'Langes',
            'Lebak',
            'Manalog',
            'Maraymaray',
            'Masimag',
            'Minsuro',
            'New Visayas',
            'Old Visayas',
            'Pinamaloy',
            'Poblacion',
            'Ponciano L. Fuentes',
            'Rizal',
            'San Antonio',
            'San Francisco',
            'San Nicolas',
            'San Roque',
            'Sinangguyan',
            'Tangkulan'
        ),
        'Quezon' => array(
            'Bukid',
            'Butong',
            'Cawayan',
            'Cebole',
            'Delapa',
            'Dulangan',
            'Kiburiao',
            'Kimagango',
            'Lagunde',
            'Lingion',
            'Mabuhay',
            'Magsaysay',
            'Manuto',
            'Merangeran',
            'Mibantang',
            'Minongan',
            'Molatambac',
            'Paitan',
            'Pamaypayan',
            'Pinilayan',
            'Poblacion',
            'Puntian',
            'Salagmanok',
            'San Isidro',
            'San Jose',
            'San Roque',
            'Santa Cruz',
            'Santo Niño',
            'Simaya'
        )
    ),
    'Basilan' => array(
        'Lamitan City' => array(
            'Arco',
            'Baiwas',
            'Baliwas',
            'Bolingat',
            'Buli-Buli',
            'Buluan',
            'Cabobo',
            'Calugusan',
            'Kulay Bato',
            'Limo-ok',
            'Lo-ok',
            'Luksumbang',
            'Maganda',
            'Malala',
            'Malinao',
            'Matatag',
            'Parangbasak',
            'Sabong',
            'Santa Clara',
            'Sengal',
            'Tandong Ahas',
            'Tumakid',
            'Ubit',
            'Ulame',
            'Malala',
            'Matatag',
            'Sabong Libot'
        ),
        'Isabela City' => array(
            'Aguada',
            'Baluno',
            'Begang',
            'Carbon',
            'Diki',
            'Isabela Proper',
            'Kapatagan Grande',
            'Kaumpurnah Zone I',
            'Kaumpurnah Zone II',
            'Kaumpurnah Zone III',
            'La Piedad',
            'Languyan',
            'Lugus',
            'Luuk',
            'Makiri',
            'Maligaya',
            'Mapatun',
            'Marketsite',
            'Menzi',
            'Panigayan',
            'Panunsulan',
            'Port Area',
            'Riverside',
            'San Antonio',
            'Santa Barbara',
            'Santa Cruz',
            'Sumagdang',
            'Sunrise Village',
            'Tabiawan',
            'Tabuk',
            'Tampalan',
            'Timpok'
        )
    ),
    'Lanao del Norte' => array(
        'Bacolod' => array(
            'Alegria',
            'Babalayan',
            'Babalayan Lower',
            'Bacolod',
            'Binuni',
            'Delabayan',
            'Esperanza',
            'Kahayagan',
            'Liangan East',
            'Liangan West',
            'Lindongan',
            'Lupagan',
            'Mahayahay',
            'Maliwanag',
            'Pagayawan',
            'Poblacion',
            'Ponol',
            'Rupagan',
            'San Jose',
            'Santa Cruz',
            'Santo Niño',
            'Suarez',
            'Talambo'
        ),
        'Kapatagan' => array(
            'Bagong Kauswagan',
            'Bagong Silang',
            'Balili',
            'Bansarvil',
            'Belis',
            'Buenavista',
            'Butadon',
            'Cathedral Falls',
            'Concepcion',
            'Curvada',
            'Donggoan',
            'Durano',
            'Graciano',
            'Kahayagan',
            'Kidalos',
            'La Libertad',
            'Lapakan',
            'Mahayahay',
            'Malinas',
            'Maranding',
            'Margos',
            'Poblacion',
            'San Isidro',
            'San Vicente',
            'Santa Cruz',
            'Santo Niño',
            'Suso',
            'Taguitic',
            'Tiacongan',
            'Tulatulahan',
            'Waterfalls'
        )
    ),
    'Agusan del Sur' => array(
        'San Francisco' => array(
            'Alegria',
            'Bayugan 3',
            'Borbon',
            'Buenasuerte',
            'Caimpugan',
            'Das-agan',
            'Ebro',
            'Hubang',
            'Karaos',
            'Ladgadan',
            'Lapinigan',
            'Lucac',
            'Mate',
            'Nuevo Trabajo',
            'Ormaca',
            'Pisa-an',
            'Poblacion',
            'Rizal',
            'San Isidro',
            'Santa Cruz',
            'Tagapua',
            'Tambis',
            'Tignog'
        ),
        'Prosperidad' => array(
            'Afga',
            'Agusan Pequeño',
            'Aurora',
            'Azpetia',
            'Bahbah',
            'Bantayan',
            'Cagdianao',
            'Cagpangi',
            'Cocornon',
            'La Caridad',
            'La Perian',
            'La Union',
            'Libertad',
            'Los Arcos',
            'Mabuhay',
            'Mapaga',
            'Napo',
            'New Maug',
            'Padiay',
            'Poblacion',
            'Prosperidad',
            'Salvacion',
            'San Jose',
            'San Martin',
            'San Salvador',
            'Santa Irene',
            'Santa Maria',
            'Santo Niño',
            'Tag-uyango',
            'Tabon'
        )
    ),
    'Zamboanga Sibugay' => array(
        'Ipil' => array(
            'Bacalan',
            'Bangkerohan',
            'Buluan',
            'Don Andres',
            'Guituan',
            'Ipil Heights',
            'Ipil Proper',
            'Logan',
            'Lower Ipil Heights',
            'Lubok',
            'Makilas',
            'Mampang',
            'Marangay',
            'Poblacion',
            'Port Holland',
            'Sanito',
            'Suclema',
            'Taway',
            'Tenan',
            'Tiayon',
            'Timalang',
            'Tomitom'
        ),
        'Kabasalan' => array(
            'Balangao',
            'Banker',
            'Boliok',
            'Bulo',
            'Buayan',
            'Caliran',
            'Concepcion',
            'Dipala',
            'Gokit',
            'Gotokan Daku',
            'Kabasalan',
            'Kapawan',
            'Lacnapan',
            'Little Baguio',
            'Lumbayao',
            'Maganay',
            'Naga-naga',
            'Nazareth',
            'Poblacion',
            'Pontevedra',
            'Sanghanan',
            'Sayao',
            'Simbol',
            'Sulo',
            'Tamin',
            'Tampalan',
            'Tigbangagan',
            'Tigbucay'
        )
    ),
    'Maguindanao del Norte' => array(
        'Parang' => array(
            'Poblacion I',
            'Poblacion II',
            'Poblacion III',
            'Poblacion IV',
            'Gadungan',
            'Guiday',
            'Gumagadong Calawag',
            'Landasan',
            'Litawan',
            'Making',
            'Manion',
            'Matibay',
            'Nituan',
            'Orandang',
            'Pinantao',
            'Polloc',
            'Sarmiento',
            'Tagudtongan',
            'Tuca-Maror',
            'Bongo Island',
            'Campo Islam',
            'Limbayan',
            'Macasandag',
            'Talisawa',
            'Tapian'
        ),
        'Matanog' => array(
            'Bayanga Norte',
            'Bayanga Sur',
            'Bugasan Norte',
            'Bugasan Sur',
            'Kidama',
            'Langco',
            'Sapad',
            'Poblacion'
        )
    ),
    'Zamboanga del Norte' => array(
        'Dipolog City' => array(
            'Barra',
            'Central',
            'Dicayas',
            'Diwan',
            'Estaka',
            'Galas',
            'Gulayon',
            'Lugdungan',
            'Minaog',
            'Miputak',
            'Olingan',
            'Punta',
            'San Jose',
            'Sicayab',
            'Sinaman',
            'Sta. Filomena',
            'Sta. Isabel',
            'Turno',
            'Upper Turno',
            'Cogon',
            'Upper Dicayas'
        ),
        'Dapitan City' => array(
            'Aliguay',
            'Baliangao',
            'Banbanan',
            'Bagting',
            'Bolong',
            'Borbon',
            'Carang',
            'Dawo',
            'Dampalan',
            'Ilaya',
            'Kauswagan',
            'Larayan',
            'Linabo',
            'Lianga',
            'Liputan',
            'Liwa-an',
            'Macleodes',
            'Maria Cristina',
            'Maria Uray',
            'Napo',
            'Oro',
            'Poblacion',
            'Polo',
            'Port Area',
            'Potol',
            'San Francisco',
            'San Nicolas',
            'San Pedro',
            'San Vicente',
            'Santa Cruz',
            'Sicayab Bocana',
            'Sibutu',
            'Sinonoc',
            'Taguilon',
            'Talisay',
            'Tambang',
            'Tapon Norte',
            'Tapon Sur',
            'Tipan',
            'Tolihon'
        )
    ),
    'Bukidnon' => array(
        'Manolo Fortich' => array(
            'Agusan Canyon',
            'Alae',
            'Dahilayan',
            'Dalirig',
            'Damilag',
            'Dicklum',
            'Guinabsan',
            'Kalugmanan',
            'Lindaban',
            'Lingion',
            'Lunocan',
            'Maluko',
            'Mambucal',
            'Mampayag',
            'Mantibugao',
            'Nancolod',
            'Poblacion',
            'San Miguel',
            'Santiago',
            'Santo Niño',
            'Tankulan',
            'Ticala'
        ),
        'Maramag' => array(
            'Anahawon',
            'Base Camp',
            'Bayabas',
            'Camp 1',
            'Colambugan',
            'Colonia',
            'Dagumba-an',
            'Dologon',
            'Kisanday',
            'Kuya',
            'La Roxas',
            'North Poblacion',
            'Panalsalan',
            'San Miguel',
            'San Roque',
            'South Poblacion',
            'Tubigon',
            'Bagontaas',
            'Panadtalan'
        )
    ),
    'Davao Oriental' => array(
        'Governor Generoso' => array(
            'Ampawan',
            'Anitap',
            'Aurora',
            'Bacolod',
            'Bacungan',
            'Banaybanay',
            'Bato',
            'Bliss',
            'Don Ruben',
            'Dapnan',
            'Don Martin Marundan',
            'Lavigan',
            'Luzon',
            'Magdug',
            'Mancal',
            'Mati',
            'Nangan',
            'Ompao',
            'Poblacion',
            'Pundaguitan',
            'Sergio Osmeña',
            'Surop',
            'Tag-uyango',
            'Tamban',
            'Tandang Sora',
            'Tibanban',
            'Tigbao',
            'Tuboran'
        ),
        'San Isidro' => array(
            'Bacungan',
            'Bitaogan',
            'Dapnan',
            'Dawo',
            'Iba',
            'Lapu-lapu',
            'Maag',
            'Mabuhay',
            'Poblacion',
            'San Miguel',
            'San Roque',
            'Santo Rosario',
            'Talisay'
        )
    ),
    'Davao de Oro' => array(
        'Nabunturan' => array(
            'Anislagan',
            'Bagong Kauswagan',
            'Bagong Silang',
            'Basak',
            'Bayabas',
            'Bukal',
            'Cabacungan',
            'Katipunan',
            'Linda',
            'Libato',
            'Libasan',
            'Magading',
            'Manduyan',
            'New Village',
            'New Visayas',
            'Ogao',
            'Poblacion',
            'San Isidro',
            'San Roque',
            'San Vicente',
            'Santa Maria',
            'Santo Niño',
            'Sasa',
            'Tagnocon',
            'Tagum North',
            'Tagum South'
        ),
        'Maco' => array(
            'Anibongan',
            'Binuangan',
            'Bucana',
            'Calabcab',
            'Concepcion',
            'Dumlan',
            'Elizalde',
            'Panibasan',
            'Gubatan',
            'Hijo',
            'Kinuban',
            'Langco',
            'Lapu-lapu',
            'Libay-libay',
            'Lumatab',
            'Magangit',
            'Mainit',
            'Malala',
            'Malibatuan',
            'Maligaya',
            'Mapaang',
            'Masara',
            'New Asturias',
            'New Barili',
            'New Leyte',
            'New Visayas',
            'Panangan',
            'Poblacion',
            'San Jose',
            'San Roque',
            'Sangab',
            'Taglawig',
            'Teresa'
        )
    ),
    'Davao del Norte' => array(
        'Tagum City' => array(
            'Apokon',
            'Bincungan',
            'Busaon',
            'Cuambogan',
            'La Filipina',
            'Liboganon',
            'Madaum',
            'Magdum',
            'Magugpo Poblacion',
            'Magugpo East',
            'Magugpo North',
            'Magugpo South',
            'Magugpo West',
            'Mankilam',
            'New Balamban',
            'Nueva Fuerza',
            'Pagsabangan',
            'Pandapan',
            'San Agustin',
            'San Isidro',
            'San Miguel',
            'Visayan Village'
        ),
        'Panabo City' => array(
            'A.O. Floirendo',
            'Cagangohan',
            'Consolacion',
            'Dapco',
            'Gredu',
            'J.P. Laurel',
            'Kasilak',
            'Katipunan',
            'Kauswagan',
            'Katualan',
            'Kiotoy',
            'Little Panay',
            'Lower Panaga',
            'Mabunao',
            'Mabantao',
            'Manay',
            'Nanyo',
            'New Malaga',
            'New Malitbog',
            'New Pandan',
            'New Visayas',
            'Poblacion',
            'Salvacion',
            'San Francisco',
            'San Nicolas',
            'San Pedro',
            'San Roque',
            'San Vicente',
            'Santa Cruz',
            'Santo Niño',
            'Southern Davao',
            'Tagpore',
            'Tibungol',
            'Upper Licanan',
            'Waterfall'
        )
    ),
    'Davao del Sur' => array(
        'Bansalan' => array(
            'Alegre',
            'Anonang',
            'Bitaug',
            'Bonifacio',
            'Buenavista',
            'Darapuay',
            'Dolo',
            'Eman',
            'Kinuskusan',
            'Labangan',
            'Libertad',
            'Linawan',
            'Mabuhay',
            'Mabunga',
            'Managa',
            'Marber',
            'New Clarin',
            'Poblacion Uno',
            'Poblacion Dos',
            'Rizal',
            'Santo Niño',
            'Sibulan',
            'Tinongtongan',
            'Union',
            'Tubod'
        ),
        'Magsaysay' => array(
            'Bacungan',
            'Balnate',
            'Dalumay',
            'Dalumay',
            'Kanapulo',
            'Kasuga',
            'Lower Bala',
            'Maibo',
            'Malala',
            'Mileb',
            'New Ilocos',
            'Poblacion',
            'San Isidro',
            'San Miguel',
            'Tacul',
            'Tagabakid',
            'Upper Bala'
        )
    ),
    'Tawi-Tawi' => array(
        'Languyan' => array(
            'Basbas',
            'Bas-Tubig',
            'Darussalam',
            'Darul Akram',
            'Kalang-Kalang',
            'Karaha',
            'Kinabungan',
            'Languyan Proper',
            'Marang-Marang',
            'Parang Pata',
            'Suba-Suba',
            'Tabu-Bato',
            'Tando-Bato'
        ),
        'Sapa-Sapa' => array(
            'Baldatal',
            'Butun',
            'Dalo-Dalo',
            'Kahikukuk',
            'Lalatan',
            'Malanta',
            'Nunuk',
            'Poblacion',
            'Sapa-Malaum',
            'Sukah-Sukah',
            'Tangngah',
            'Tong-Tong',
            'Tongsibalo'
        )
    ),
    'Misamis Oriental' => array(
        'Villanueva' => array(
            'Balacanas',
            'Dayawan',
            'Katipunan',
            'Kimaya',
            'Poblacion',
            'San Martin',
            'Santa Cruz',
            'Tagcatong',
            'Vinapor'
        ),
        'Jasaan' => array(
            'Aplaya',
            'Bobontugan',
            'Corrales',
            'Danao',
            'Jampason',
            'Kimaya',
            'Lower Jasaan',
            'Luz Banzon',
            'Natubo',
            'Poblacion Lower',
            'Poblacion Upper',
            'San Antonio',
            'San Isidro',
            'San Nicolas',
            'Solana',
            'Taytay',
            'Tubigan',
            'Upper Jasaan'
        )
    ),
    'Sulu' => array(
        'Jolo' => array(
            'Alat',
            'Asturias',
            'Busbus',
            'Chinese Pier',
            'Hadji Butu',
            'Kasalamatan',
            'Latih',
            'Marina',
            'Port Area',
            'San Raymundo',
            'Serantes',
            'Takut-Takut',
            'Tulay',
            'Walled City'
        ),
        'Indanan' => array(
            'Adjid',
            'Bandang',
            'Buansa',
            'Kajatian',
            'Kan Islam',
            'Karawan',
            'Kuppong',
            'Lambayong',
            'Manggis',
            'Paligue',
            'Panabuan',
            'Pasil',
            'Poblacion',
            'Suba-Suba',
            'Tagbak',
            'Timbangan',
            'Tubig Dakulah',
            'Tubig-Mampallam'
        )
    ),
    'Zamboanga del Norte' => array(
        'Sindangan' => array(
            'Bago',
            'Balok',
            'Binuangan',
            'Bitoon',
            'Bucana',
            'Calatunan',
            'Calucap',
            'Dapaon',
            'Dicoyong',
            'Disud',
            'Donkey',
            'Goleo',
            'Jose Dalman',
            'La Roche',
            'Lapero',
            'Lawigan',
            'Lipas',
            'Maras',
            'Misok',
            'Piao',
            'Poblacion',
            'Siari',
            'Siare',
            'Talinga',
            'Tigbao'
        ),
        'Siayan' => array(
            'Balakan',
            'Binalbal',
            'Datagan',
            'Dinasan',
            'Domogok',
            'Gonayen',
            'Guibo',
            'Gunyan',
            'Kapatagan',
            'Litolet',
            'Macasing',
            'Manipis',
            'Moyo',
            'Paranglumba',
            'Piacan',
            'Poblacion',
            'Polayo',
            'Siayan Proper',
            'Sindangan',
            'Situbo',
            'Tina'
        )
    ),
    'Agusan del Norte' => array(
        'Carmen' => array(
            'Cahayagan',
            'Gosoon',
            'Manoligao',
            'Poblacion',
            'Rojales',
            'San Agustin',
            'Tagcatong',
            'Vinapor'
        ),
        'Kitcharao' => array(
            'Bangayan',
            'Canaway',
            'Crossing',
            'Hinimbangan',
            'Jaguimitan',
            'Mahayahay',
            'Poblacion',
            'San Isidro',
            'San Roque',
            'Sangay',
            'Tinago'
        )
    ),
    'Surigao del Sur' => array(
        'Lianga' => array(
            'Anibongan',
            'Ban-as',
            'Banahao',
            'Baucawe',
            'Diatagon',
            'Ganayon',
            'Liatimco',
            'Manyayay',
            'Poblacion',
            'St. Christine',
            'San Isidro',
            'San Pedro'
        ),
        'San Agustin' => array(
            'Bretania',
            'Buhatan',
            'Buhisan',
            'Gata',
            'Janipaan',
            'Kauswagan',
            'Oteiza',
            'Poblacion',
            'Pong-on',
            'Salvacion',
            'San Roque',
            'Sto. Niño'
        )
    ),
    'Maguindanao del Norte' => array(
        'Datu Paglas' => array(
            'Poblacion',
            'Bonawan',
            'Damawato',
            'Dalumang',
            'Datang',
            'Kalumenga',
            'Katil',
            'Madidis',
            'Malala',
            'Mangadeg',
            'Palao sa Buto',
            'Sepaka'
        ),
        'Rajah Buayan' => array(
            'Poblacion',
            'Baital',
            'Bakat',
            'Malibpolok',
            'Mileb',
            'Panadtaban',
            'Pidsandawan',
            'Sampao',
            'Sapakan',
            'Tabungao'
        )
    ),
    'Lanao del Norte' => array(
        'Tubod' => array(
            'Poblacion',
            'Barakanas',
            'Baris',
            'Bualan',
            'Bulod',
            'Caniogan',
            'Dalamas',
            'Kalilangan',
            'Licapao',
            'Lumba-Bayabao',
            'Palao',
            'Pangao',
            'Pinpin',
            'Santo Niño',
            'Taden',
            'Tangueguiron',
            'Theresa',
            'Tingin'
        ),
        'Sultan Naga Dimaporo' => array(
            'Poblacion',
            'Bangaan',
            'Bauyan',
            'Calabao',
            'Dalama',
            'Kauswagan',
            'Lantawan',
            'Mabuhay',
            'Mahayahay',
            'Marupo',
            'Pandanan',
            'Payong',
            'Pikinit',
            'Ramain',
            'Rebucon',
            'Santo Niño',
            'Tagulo',
            'Tambo'
        )
    ),
    'South Cotabato' => array(
        'Surallah' => array(
            'Poblacion',
            'Buenavista',
            'Centrala',
            'Dajay',
            'Lamian',
            'Lapu',
            'Lumbac',
            'Lunen',
            'Mabuhay',
            'Moloy',
            'Naci',
            'Ponol',
            'San Isidro',
            'San Jose',
            'San Vicente',
            'Santa Cruz',
            'Tubiala',
            'Upper Sepaka',
            'Veterans'
        ),
        'Lake Sebu' => array(
            'Poblacion',
            'Bacdulong',
            'Denlag',
            'Halilan',
            'Klubi',
            'Lake Lahit',
            'Lamcade',
            'Lantawan',
            'Lamdalag',
            'Lumbayao',
            'Luhi',
            'Malbang',
            'Ned',
            'Poblacion',
            'Seloton',
            'Talisay',
            'Takunel',
            'Tebucon',
            'Tilokan',
            'Tubod',
            'Upper Maculan'
        )
    ),
    'Davao Oriental' => array(
        'Mati City' => array(
            'Badas',
            'Bobon',
            'Buso',
            'Central',
            'Dahican',
            'Dawis',
            'Don Martin Marundan',
            'Lapu-lapu',
            'Lawigan',
            'Libertad',
            'Lunao',
            'Macambol',
            'Mamali',
            'Mayo',
            'Sainz',
            'Sanghay',
            'Taguibo',
            'Tagabakid',
            'Tagbiti',
            'Tamisan'
        ),
        'Lupon' => array(
            'Poblacion',
            'Bagumbayan',
            'Cabadiangan',
            'Calapagan',
            'Cocornon',
            'Corporacion',
            'Don Mariano Marcos',
            'Ilangay',
            'Langka',
            'Lantawan',
            'Limbahan',
            'Macangao',
            'Magsaysay',
            'Mahayahay',
            'Marayag',
            'New Visayas',
            'Poblacion',
            'San Isidro',
            'San Jose',
            'Santo Niño',
            'Tag-Ugpo'
        )
    ),
    'Davao del Norte' => array(
        'New Corella' => array(
            'Poblacion',
            'Cabidianan',
            'Carcor',
            'Del Monte',
            'Del Pilar',
            'El Salvador',
            'Limba-an',
            'Mabuhay',
            'Mesaoy',
            'New Bohol',
            'New Cortez',
            'New Sambog',
            'Patrocenio',
            'San Roque',
            'Santa Cruz',
            'Santa Fe',
            'Santo Niño',
            'Suawon',
            'San Jose'
        ),
        'Kapalong' => array(
            'Poblacion',
            'Capungagan',
            'Florida',
            'Gupitan',
            'Katipunan',
            'Luna',
            'Mabunao',
            'Mabantao',
            'Maniki',
            'Pag-asa',
            'Semong',
            'Sua-on',
            'Tibungol'
        )
    ),
    'Sultan Kudarat' => array(
        'Tacurong City' => array(
            'Poblacion',
            'Baras',
            'Buenavista',
            'Calean',
            'Carmen',
            'D. Lotilla',
            'Griño',
            'New Carmen',
            'New Isabela',
            'New Passi',
            'San Antonio',
            'San Emmanuel',
            'San Pablo',
            'San Vicente',
            'Santa Cruz',
            'Tina'
        ),
        'Isulan' => array(
            'Poblacion',
            'Bambad',
            'Bual',
            'D. Lotilla',
            'Dansuli',
            'Impao',
            'Kalawag I',
            'Kalawag II',
            'Kalawag III',
            'Kenram',
            'Kolambug',
            'Kudanding',
            'Lagandang',
            'Laguilayan',
            'Mapantig',
            'New Pangasinan',
            'Sampao',
            'Santa Clara'
        )
    ),
    'Agusan del Sur' => array(
        'Bayugan City' => array(
            'Poblacion',
            'Calaitan',
            'Charito',
            'Fili',
            'Gethsemane',
            'Hamogaway',
            'Katipunan',
            'Maygatasan',
            'Noli',
            'Osmeña',
            'Poblacion',
            'Pinagalaan',
            'Sagmone',
            'Salbu',
            'Salvacion',
            'San Jose',
            'Santa Irene',
            'Santa Teresita',
            'Santo Niño',
            'Taglatawan',
            'Taglibas',
            'Tagubay',
            'Villa Undayon'
        ),
        'Sibagat' => array(
            'Poblacion',
            'Afga',
            'Anahawan',
            'Banagbanag',
            'Del Rosario',
            'El Rio',
            'Ilihan',
            'Kioya',
            'Magkalape',
            'Magsaysay',
            'Mahayahay',
            'New Tubigon',
            'Padiay',
            'Perez',
            'Poblacion',
            'San Isidro',
            'San Vicente',
            'Santa Cruz',
            'Santa Maria',
            'Sinai',
            'Tabon-tabon',
            'Tag-uyango'
        )
    ),
    'Zamboanga Sibugay' => array(
        'Buug' => array(
            'Poblacion',
            'Bagong Silang',
            'Basalem',
            'Bawang',
            'Bulaan',
            'Datu Panas',
            'Del Monte',
            'Guintuloan',
            'Hadji Muhammad',
            'Lantawan',
            'Mabuhay',
            'Maganay',
            'Muyo',
            'Pamintayan',
            'San Jose',
            'Talamimi',
            'Villacastor'
        ),
        'Kumalarang' => array(
            'Poblacion',
            'Bagong Silang',
            'Batu-batu',
            'Bogayo',
            'Boyugan',
            'Bualan',
            'Caliran',
            'Diplo',
            'Gawil',
            'Katipunan',
            'Lantawan',
            'Limason',
            'Lingcangan',
            'Looc',
            'Lukuan',
            'Lunib',
            'Picanan',
            'Salagmanok',
            'Sulo',
            'Tamin',
            'Tampalan',
            'Tigbangagan',
            'Tigbucay'
        )
    ),
    'North Cotabato' => array(
        'Kidapawan City' => array(
            'Poblacion',
            'Amas',
            'Balabag',
            'Balindog',
            'Binoligan',
            'Ginatilan',
            'Ilomavis',
            'Kalasungay',
            'Lanao',
            'Linabo',
            'Macabolig',
            'Malinan',
            'Manongol',
            'Marbel',
            'Mateo',
            'New Bohol',
            'Nuangan',
            'Paco',
            'Perez',
            'San Isidro',
            'San Roque',
            'Santo Niño',
            'Sibulawan',
            'Singao',
            'Sudapin',
            'Sumbac'
        ),
        'Midsayap' => array(
            'Poblacion',
            'Anonang',
            'Bagolibas',
            'Baliwagan',
            'Bual Norte',
            'Bual Sur',
            'Central Glad',
            'Damatulan',
            'Kapinpilan',
            'Kasila',
            'Kimagango',
            'Kiwanan',
            'Kudarangan',
            'Ladtingan',
            'Lagumbingan',
            'Lomopog',
            'Lower Glad',
            'Macasendeg',
            'Malamote',
            'Mibantang',
            'Nabalawag',
            'Olandang',
            'Palongoguen',
            'Rangeban',
            'Salunayan',
            'Sambulawan',
            'San Pedro',
            'Tugal'
        )
    ),
    'Surigao del Norte' => array(
        'Placer' => array(
            'Poblacion',
            'Amoslog',
            'Anislagan',
            'Bad-as',
            'Bangaan',
            'Bulalacao',
            'Cagdianao',
            'Cagpangi',
            'Daywan',
            'Ellaperal',
            'Ipil',
            'Lakandula',
            'Mabini',
            'Macalaya',
            'Magsaysay',
            'Nonoc',
            'Panag',
            'Panatagan',
            'San Isidro',
            'Sanafe',
            'Suyoc',
            'Taganito',
            'Tagpangahoy',
            'Talisay'
        ),
        'Malimono' => array(
            'Poblacion',
            'Binocaran',
            'Buliang',
            'Buluan',
            'Cagtinae',
            'Can-age',
            'Cayawan',
            'Doro',
            'Hanagdong',
            'Karihatag',
            'Masgad',
            'Pili',
            'San Isidro',
            'Tinago'
        )
    ),
    'Misamis Occidental' => array(
        'Ozamiz City' => array(
            'Poblacion',
            'Aguada',
            'Bacolod',
            'Baliangao',
            'Bongbong',
            'Bulao',
            'Calabayan',
            'Capucao C.',
            'Capucao P.',
            'Carangan',
            'Carmen',
            'Catadman-Manabay',
            'Cavinte',
            'Dalapang',
            'Diguan',
            'Dimaluna',
            'Doña Consuelo',
            'Ditoray',
            'Dumagoc',
            'Gatas',
            'Gubac',
            'Kagawasan',
            'Kahayagan',
            'Kalasan',
            'Kawit',
            'La Suerte',
            'Lala',
            'Lenienza',
            'Lison Valley',
            'Lower Sibatang',
            'Lumad',
            'Macasing',
            'Manga',
            'Pantaon',
            'San Antonio',
            'San Roque',
            'Santa Cruz',
            'Stimson Abordo',
            'Tabid',
            'Tinago',
            'Triunfo'
        ),
        'Tangub City' => array(
            'Poblacion I',
            'Poblacion II',
            'Aquino',
            'Balatacan',
            'Banglay',
            'Bintana',
            'Caniangan',
            'Catagan',
            'Dicamay',
            'Garang',
            'Guinabot',
            'Isidro D. Tan',
            'Kauswagan',
            'Kimat',
            'Lorenzo Tan',
            'Mantic',
            'Manga',
            'Migcanaway',
            'Minsubong',
            'Owayan',
            'Panalsalan',
            'Pangabuan',
            'Pangi',
            'Prenza',
            'Silanga',
            'Silangon',
            'Sumirap',
            'Taguite',
            'Tituron',
            'Tuburan',
            'Unidos'
        )
    ),
    'Zamboanga del Sur' => array(
        'Pagadian City' => array(
            'Poblacion',
            'Balangasan',
            'Balintawak',
            'Baloyboan',
            'Banale',
            'Bogo',
            'Bomba',
            'Bulatok',
            'Dampalan',
            'Danlugan',
            'Dao',
            'Datagan',
            'Deborok',
            'Ditoray',
            'Dumagoc',
            'Gatas',
            'Gubac',
            'Kagawasan',
            'Kahayagan',
            'Kalasan',
            'Kawit',
            'Lala',
            'Lenienza',
            'Lison Valley',
            'Lower Sibatang',
            'Lumad',
            'Macasing',
            'Manga',
            'Muricay',
            'Napolan',
            'Palpalan',
            'Poblacion',
            'Poloyagan',
            'San Jose',
            'San Pedro',
            'Santa Cruz',
            'Santiago',
            'Tiguma',
            'Tuburan',
            'Upper Sibatang',
            'White Beach'
        ),
        'Molave' => array(
            'Poblacion',
            'Ariosa',
            'Bagong Argao',
            'Bagong Gutlang',
            'Blancia',
            'Bogo Capalaran',
            'Culo',
            'Dalaon',
            'Dipolo',
            'Dontulan',
            'Mabuhay',
            'Madasigon',
            'Makuguihon',
            'Maloloy-on',
            'Miligan',
            'Parasan',
            'Rizal',
            'Santo Rosario',
            'Silangit',
            'Sudlon',
            'Toling'
        )
    ),
    'Sarangani' => array(
        'Alabel' => array(
            'Poblacion',
            'Alegria',
            'Bagacay',
            'Baluntay',
            'Datal Anggas',
            'Domolok',
            'Kawas',
            'Ladol',
            'Maribulan',
            'Pag-asa',
            'Paraiso',
            'Spring',
            'Tokawal'
        ),
        'Glan' => array(
            'Poblacion',
            'Baliton',
            'Bantayan',
            'Batulaki',
            'Big Margus',
            'Cablalan',
            'Calatunan',
            'Capitan',
            'Cross',
            'Datalag',
            'E. Alegado',
            'Gumasa',
            'Ilisan',
            'Kaltuad',
            'Kapatan',
            'Lago',
            'Lagunde',
            'Ligayas',
            'Lungaog',
            'Madalsan',
            'Malapatan',
            'New Aklan',
            'Poblacion',
            'Rio del Pilar',
            'San Jose',
            'San Vicente',
            'Small Margus',
            'Sufatubo',
            'Taluya',
            'Tango'
        )
    ),
    'Dinagat Islands' => array(
        'San Jose' => array(
            'Aurora (Pob.)',
            'Aurelio (Pob.)',
            'Cuarinta',
            'Don Ruben',
            'Jacquez',
            'Luna',
            'Mahayahay',
            'Matingbe',
            'San Jose (Pob.)',
            'San Juan (Pob.)',
            'San Pablo (Pob.)',
            'Sta. Cruz',
            'Wilson'
        ),
        'Basilisa' => array(
            'Benglen',
            'Catadman',
            'Cortes',
            'Doña Helen',
            'Edera',
            'Geotina',
            'Imee',
            'Melgar',
            'Navarro',
            'Osmeña',
            'Poblacion',
            'Puerto Princesa',
            'Rita',
            'Roxas',
            'San Miguel',
            'Sering',
            'Sombrado',
            'Tag-abaca',
            'Villa',
            'Villa Ecleo'
        )
    ),
    'Camiguin' => array(
        'Mambajao' => array(
            'Poblacion',
            'Agoho',
            'Anito',
            'Balbagon',
            'Baylao',
            'Benoni',
            'Bug-ong',
            'Kuguita',
            'Magting',
            'Naasag',
            'Pandan',
            'Soro-soro',
            'Tagdo',
            'Tupsan',
            'Yumbing'
        ),
        'Mahinog' => array(
            'Poblacion',
            'Benoni',
            'Binaliwan',
            'Hubangon',
            'Owakan',
            'Puntod',
            'San Isidro',
            'San Jose',
            'San Miguel',
            'San Roque',
            'Santo Niño',
            'Tubod'
        )
    ),
    'Misamis Oriental' => array(
        'El Salvador City' => array(
            'Poblacion',
            'Amao',
            'Bolisong',
            'Cogon',
            'Himaya',
            'Hinigdaan',
            'Kalabaylabay',
            'Kibonbon',
            'Molugan',
            'Poblacion',
            'Sambulawan',
            'Sinaloc',
            'Taytay',
            'Ulaliman'
        ),
        'Balingasag' => array(
            'Poblacion',
            'Balagnan',
            'Baliwagan',
            'Binitinan',
            'Blanco',
            'Calawag',
            'Camuayan',
            'Cogon',
            'Dansuli',
            'Dumarait',
            'Hermano',
            'Kibanban',
            'Linabu',
            'Linggangao',
            'Mambaya',
            'Manticao',
            'Napaliran',
            'Quezon',
            'Rosario',
            'San Isidro',
            'San Vicente',
            'Samay',
            'Talisayan',
            'Tugas'
        )
    ),
    'Sultan Kudarat' => array(
        'Bagumbayan' => array(
            'Poblacion',
            'Bai Sarifinang',
            'Biwang',
            'Bulok',
            'Buluan',
            'Daguma',
            'Kabulanan',
            'Kapaya',
            'Kinayao',
            'Masiag',
            'Napungas',
            'South Sepaka',
            'Sison',
            'Tuka'
        ),
        'Lebak' => array(
            'Poblacion',
            'Barangay A',
            'Barangay B',
            'Barangay C',
            'Basak',
            'Bolesan',
            'Capilan',
            'Datu Karon',
            'Dolangan',
            'Kalamongog',
            'Keytodac',
            'Kinudalan',
            'Ligayas',
            'Pasandalan',
            'Purikay',
            'Salagmanok',
            'Taguilon',
            'Tibpuan',
            'Tran'
        )
    ),
    'South Cotabato' => array(
        'Koronadal City' => array(
            'Poblacion',
            'Assumption',
            'Buenavista',
            'Cacub',
            'Caloocan',
            'Concepcion',
            'General Paulino Santos',
            'Mabini',
            'Magsaysay',
            'Mambucal',
            'Morales',
            'Namnama',
            'New Pangasinan',
            'Paraiso',
            'Rotonda',
            'San Isidro',
            'San Jose',
            'San Roque',
            'Santa Cruz',
            'Santo Niño',
            'Saravia',
            'Zone I',
            'Zone II',
            'Zone III',
            'Zone IV'
        ),
        'Polomolok' => array(
            'Poblacion',
            'Bentung',
            'Caniangan',
            'Crossing Palkan',
            'Glamang',
            'Kinilis',
            'Klinan 6',
            'Koronadal Proper',
            'Lapu',
            'Landan',
            'Lumbo',
            'Magsaysay',
            'Maligo',
            'Pagalungan',
            'Palkan',
            'Poblacion',
            'Rubber',
            'Silway 7',
            'Silway 8',
            'Sulit',
            'Upper Klinan'
        )
    ),
    'Bukidnon' => array(
        'Talakag' => array(
            'Poblacion',
            'Basak',
            'Baylanan',
            'Cacaon',
            'Dagundalahon',
            'Dagumbaan',
            'Dominorog',
            'Indulang',
            'Lantud',
            'Lapok',
            'Liguron',
            'Lingi-on',
            'Lirongan',
            'Miarayon',
            'Sagaran',
            'San Antonio',
            'San Miguel',
            'San Rafael',
            'Santo Niño',
            'Tag-uyango',
            'Tagbak',
            'Tikalaan'
        ),
        'Pangantucan' => array(
            'Poblacion',
            'Adtuyon',
            'Bacusanon',
            'Bangahan',
            'Concepcion',
            'Gandingan',
            'Kimatuhaw',
            'Kisolon',
            'Langcataon',
            'Lantapan',
            'Madaya',
            'Mendis',
            'Napungas',
            'New Eden',
            'Payad',
            'Ponol',
            'Pueblo',
            'San Francisco',
            'San Miguel'
        )
    ),
    'Basilan' => array(
        'Tipo-Tipo' => array(
            'Poblacion',
            'Badja',
            'Banah',
            'Bangcuang',
            'Bohelebung',
            'Buli-Buli',
            'Tipo-Tipo Proper',
            'Lagayas',
            'Limbo-Upas',
            'Magcawa',
            'Silangkum',
            'Taguimon'
        ),
        'Maluso' => array(
            'Poblacion',
            'Abong-Abong',
            'Alat',
            'Batungal',
            'Calang-Canas',
            'Fuente',
            'Guanan',
            'Haina',
            'Lambayong',
            'Limbubong',
            'Lower Mahayahay',
            'Port Holland',
            'Taberlongan',
            'Tamuk',
            'Townsite',
            'Upper Mahayahay'
        )
    ),
    'Lanao del Norte' => array(
        'Iligan City' => array(
            'Poblacion',
            'Abuno',
            'Acmac',
            'Bagong Silang',
            'Bonbonon',
            'Bunawan',
            'Dalipuga',
            'Del Carmen',
            'Digkilaan',
            'Hinaplanon',
            'Hindang',
            'Kabacsanan',
            'Kalilangan',
            'Kiwalan',
            'Luinab',
            'Mahayahay',
            'Mainit',
            'Mandulog',
            'Maria Cristina',
            'Panoroganan',
            'Puga-an',
            'Rogongon',
            'San Miguel',
            'San Roque',
            'Santa Elena',
            'Santo Rosario',
            'Saray',
            'Suarez',
            'Tibanga',
            'Tipanoy',
            'Tomas L. Cabili',
            'Tubod',
            'Upper Hinaplanon',
            'Villa Verde'
        ),
        'Baroy' => array(
            'Poblacion',
            'Andil',
            'Bagong Silang',
            'Banban',
            'Cabasagan',
            'Dalama',
            'Libertad',
            'Lindongan',
            'Lipatan',
            'Lupa-an',
            'Mabini',
            'Manan-ao',
            'Pange',
            'Poblacion',
            'Raw-an',
            'Riverside',
            'Sagadan',
            'Santo Niño',
            'Tinukoran'
        )
    ),
    'Davao del Sur' => array(
        'Digos City' => array(
            'Poblacion',
            'Aplaya',
            'Balabag',
            'Binaton',
            'Cogon',
            'Colorado',
            'Dawis',
            'Dulangan',
            'Goma',
            'Igpit',
            'Kapatagan',
            'Lungag',
            'Mahayag',
            'Matti',
            'Melilia',
            'Pandanon',
            'Ruparan',
            'San Jose',
            'San Miguel',
            'Sinawilan',
            'Soong',
            'Tiguman',
            'Tres de Mayo',
            'Zone 1',
            'Zone 2',
            'Zone 3'
        ),
        'Santa Cruz' => array(
            'Poblacion',
            'Astorga',
            'Bato',
            'Coronon',
            'Darong',
            'Inawayan',
            'Jose Rizal',
            'Matutungan',
            'Mintal',
            'Poblacion',
            'Sibulan',
            'Sinaragan',
            'Tagabuli',
            'Tibolo',
            'Tuban',
            'Zone 1',
            'Zone 2',
            'Zone 3'
        )
    ),
    'Sarangani' => array(
        'Kiamba' => array(
            'Poblacion',
            'Badtasan',
            'Datu Dani',
            'Gasi',
            'Kapate',
            'Katipunan',
            'Kayupo',
            'Kling',
            'Lagundi',
            'Lamian',
            'Lomuyon',
            'Malalag',
            'Nalus',
            'Poblacion',
            'Salakit',
            'Sambolawan',
            'Tablao',
            'Tamadang',
            'Tambilil',
            'Tambilil Proper',
            'Tambis',
            'Tayawan'
        ),
        'Maasim' => array(
            'Poblacion',
            'Amsipit',
            'Bales',
            'Colon',
            'Daliao',
            'Kabatiol',
            'Kanalo',
            'Kulape',
            'La Union',
            'Ligaya',
            'Lumatab',
            'Mahayag',
            'Malbang',
            'Nomoh',
            'Pananag',
            'Poblacion',
            'Seven Hills',
            'Tonong',
            'Tubogak'
        )
    ),
    'Agusan del Norte' => array(
        'Butuan City' => array(
            'Poblacion',
            'Agusan Pequeño',
            'Ambago',
            'Ampayon',
            'Anticala',
            'Anitap',
            'Baan KM 3',
            'Babag',
            'Bading',
            'Bancasi',
            'Banza',
            'Buenavista',
            'Bugabungan',
            'Calabao',
            'Dagupan',
            'Datu Silongan',
            'Dona Telesfora',
            'Doongan',
            'Fort Poyohon',
            'Golden Ribbon',
            'Holy Redeemer',
            'Humabon',
            'Kinamlutan',
            'Lapu-lapu',
            'Leon Kilat',
            'Libertad',
            'Limaha',
            'Lumbocan',
            'Maibu',
            'Mandamo',
            'Manuel Segundo',
            'Mangayao',
            'Matabao',
            'Maug',
            'New Society Village',
            'Obrero',
            'Ong Yiu',
            'Poblacion',
            'Rajah Soliman',
            'San Ignacio',
            'San Mateo',
            'San Vicente',
            'Santa Ana',
            'Santo Niño',
            'Sikatuna',
            'Silongan',
            'Sumile',
            'Tagabaca',
            'Taguibo',
            'Taligaman',
            'Tandang Sora',
            'Tiniwisan',
            'Tungao',
            'Villa Kananga',
            'Villa Obrero'
        ),
        'Cabadbaran City' => array(
            'Poblacion',
            'Bayabas',
            'Calibunan',
            'Concepcion',
            'Del Pilar',
            'Katipunan',
            'Kauswagan',
            'La Union',
            'Mabini',
            'Mahaba',
            'Puting Bato',
            'Rosario',
            'Sanghan',
            'Soriano',
            'Tolosa'
        )
    ),
    'Zamboanga City' => array(
        'Ayala' => array(
            'Ayala',
            'Baluno',
            'Boalan',
            'Bunguiao',
            'Cawit',
            'Curuan',
            'Culianan',
            'Divisoria',
            'Guiwan',
            'La Paz',
            'Labuan',
            'Lamisahan',
            'Landang Gua',
            'Lanzones',
            'Lapakan',
            'Latuan',
            'Licomo',
            'Limaong',
            'Limpapa',
            'Lubigan',
            'Lumayang',
            'Maasin',
            'Malagutay',
            'Mampang',
            'Manalipa',
            'Mariki',
            'Mercedes',
            'Muti',
            'Pamucutan',
            'Pangapuyan',
            'Panubigan',
            'Pasilmanta',
            'Pasonanca',
            'Patalon',
            'Putik',
            'Quiniput',
            'Recodo',
            'Rio Hondo',
            'Salaan',
            'San Jose Cawa-Cawa',
            'San Jose Gusu',
            'San Ramon',
            'San Roque',
            'Sangali',
            'Santa Barbara',
            'Santa Catalina',
            'Santa Maria',
            'Santo Niño',
            'Sibulao',
            'Sinubong',
            'Sinunuc',
            'Tagasilay',
            'Taguiti',
            'Talabaan',
            'Talisayan',
            'Talon-Talon',
            'Taluksangay',
            'Tetuan',
            'Tictapul',
            'Tigbalabag',
            'Tigtabon',
            'Tolosa',
            'Tugbungan',
            'Tumalutab',
            'Tumitus',
            'Victoria',
            'Vitali',
            'Zambowood',
            'Zone I',
            'Zone II',
            'Zone III',
            'Zone IV'
        ),
        'Tumaga' => array(
            'Arena Blanco',
            'Baliwasan',
            'Calarian',
            'Campo Islam',
            'Canelar',
            'Mariki',
            'Rio Hondo',
            'San Jose Cawa-cawa',
            'Sinunuc',
            'Talipao',
            'Talon-Talon',
            'Taluksangay',
            'Tetuan',
            'Tictapul',
            'Tigbalabag',
            'Tigtabon',
            'Tolosa',
            'Tugbungan',
            'Tumalutab',
            'Tumitus',
            'Victoria',
            'Vitali',
            'Zambowood',
            'Zone I',
            'Zone II',
            'Zone III',
            'Zone IV'
        )
    ),
    'Sulu' => array(
        'Jolo' => array(
            'Poblacion',
            'Alat',
            'Asturias',
            'Busbus',
            'Chinese Pier',
            'Hadji Butu',
            'Kasalamatan',
            'Latih',
            'Marina',
            'Port Area',
            'San Raymundo',
            'Serantes',
            'Takut-Takut',
            'Tulay',
            'Walled City'
        ),
        'Patikul' => array(
            'Poblacion',
            'Anuling',
            'Bangkal',
            'Batu-Batu',
            'Bawis',
            'Buli-Buli',
            'Bungkaung',
            'Danag',
            'Ganassi',
            'Kadday',
            'Kapuk',
            'Kiput',
            'Kusain',
            'Lahing-Lahing',
            'Latih-Latih',
            'Ligayan',
            'Lunggang',
            'Maligay',
            'Mangal',
            'Mantan',
            'Manubul',
            'Marang',
            'Mipantaw',
            'Pandan-Pandan',
            'Pangdan',
            'Pansul',
            'Parang',
            'Poblacion',
            'Punungan',
            'Saidu',
            'Sambulawan',
            'Sandah',
            'Santa Maria',
            'Sapah Malaum',
            'Sipangkot',
            'Sitangkai',
            'Talipao',
            'Tandu-Bagua',
            'Tandu-Bato',
            'Tangkuan',
            'Tapian',
            'Tarawakan',
            'Timpok',
            'Tugas',
            'Tukay',
            'Tumangas',
            'Tunhud',
            'Upper Sinumaan'
        )
    ),
    'Bukidnon' => array(
        'Malaybalay City' => array(
            'Poblacion',
            'Aglayan',
            'Bangcud',
            'Busdi',
            'Cabangahan',
            'Canasugan',
            'Capitan Angel',
            'Dalwangan',
            'Imbayao',
            'Kalasungay',
            'Kulaman',
            'Laguitas',
            'Linabo',
            'Magsaysay',
            'Managok',
            'Manalog',
            'Mapayag',
            'Miglamin',
            'Patpat',
            'Poblacion',
            'Saint Peter',
            'San Jose',
            'San Martin',
            'Santo Niño',
            'Silae',
            'Simaya',
            'Sumpong',
            'Violeta',
            'Zamboanguita'
        ),
        'Valencia City' => array(
            'Bagonta-as',
            'Barobo',
            'Batangan',
            'Colonia',
            'Guinoyoran',
            'Kahaponan',
            'Kilabong',
            'Lilingayon',
            'Lumbo',
            'Lurogan',
            'Maapag',
            'Mabuhay',
            'Mailag',
            'Mt. Nebo',
            'Nabag-o',
            'Pinatilan',
            'Poblacion',
            'San Carlos',
            'Sinabuagan',
            'Sugod',
            'Tongantongan',
            'Tugaya',
            'Vintar'
        )
    )
);

if(isset($_POST['province'])) {
    if(!isset($_POST['municipality'])) {
        // Get municipalities for selected province
        $province = $_POST['province'];
        if(isset($municipalities[$province])) {
            echo json_encode($municipalities[$province]);
        } else {
            echo json_encode([]);
        }
    } else {
        // Get barangays for selected municipality
        $province = $_POST['province'];
        $municipality = $_POST['municipality'];
        if(isset($barangays[$province][$municipality])) {
            echo json_encode($barangays[$province][$municipality]);
        } else {
            echo json_encode([]);
        }
    }
}
?>
